version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_music_bot
    volumes:
      - .:/app
    environment:
      - BOT_TOKEN=your_telegram_token_here
    restart: unless-stopped
