version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_music_bot
    volumes:
      - .:/app
    environment:
      - BOT_TOKEN=7725505257:AAG4DpKOUisVOZA16-Fn8ALb_Sxp6zVnRLQ
    restart: unless-stopped
